name: Update Bing Wallpaper

on:
  schedule:
    - cron: "30 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - run: mkdir -p archive/

      - name: Update Bing Wallpaper
        run: python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: Bing Wallpaper Data Auto Backup
          path: archive/

      - run: rm -rf archive/

      - name: Commit files
        run: git commit -a -m "Auto update at $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
